-- AlterTable
ALTER TABLE `User` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `totalComments` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalFollowers` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalFollowing` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalLikes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalPosts` INTEGER NOT NULL DEFAULT 0;
